services:
  streamlit:
    build:
      context: .
    container_name: streamlit-amazon-sales-dev
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./app.py:/app/app.py
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
    restart: unless-stopped 